image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - "Maven Build"
  - "Docker Build"

Building Executable JAR:
  image: maven:3-jdk-8
  stage: "Maven Build"
  script: mvn clean install
  artifacts:
    expire_in: 1 hour
    paths:
      - target/dictionbot-runner.jar

Building Docker Image:
  stage: "Docker Build"
  script:
    - sh docker-builder
  only:
    - master