image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - "Build"
  - "Deploy"

Docker Image Release:
  stage: "Build"
  variables:
    DOCKER_USERNAME: $DOCKERHUB_USERNAME
    DOCKER_PASSWORD: $DOCKERHUB_TOKEN
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build -t shibme/dictionbot --platform linux/amd64,linux/arm64,linux/arm/v7 --push .
    - docker logout
  only:
    - master

DictionBot Deployment:
  stage: "Deploy"
  trigger: shibme/dictionbot-deployment
  only:
    - master