image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - deploy

Maven Build:
  image: maven:3-jdk-8
  stage: build
  script: mvn clean install
  artifacts:
    paths:
      - target/dictionbot-runner.jar

Publishing Docker Image:
  stage: deploy
  script:
    - sh docker-builder
  only:
    - master