image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - "Build"
  - "Release"
  - "Deploy"

Java Build:
  image: maven:3-jdk-8
  stage: "Build"
  script: mvn clean install
  artifacts:
    expire_in: 1 hour
    paths:
      - target/dictionbot-runner.jar

Docker Image Release:
  stage: "Release"
  script:
    - sh docker-builder
  only:
    - master

DictionBot Deployment:
  stage: "Deploy"
  trigger: shibme/dictionbot-deployment
  only:
    - master