builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'