#!/usr/bin/env bash
DOCKER_VERSION_RESPONSE=$(docker -v)
EXPECTED_RESPONSE="Docker version "
if test "${DOCKER_VERSION_RESPONSE#*$EXPECTED_RESPONSE}" != "$DOCKER_VERSION_RESPONSE"; then
  #Setting default container name if not set
  if [ -z "$DICTIONBOT_CONTAINER" ]; then
    export DICTIONBOT_CONTAINER="dictionbot"
  fi
  echo "Attempting to stop and remove any instances of DictionBot..."
  docker stop $DICTIONBOT_CONTAINER || true && docker rm $DICTIONBOT_CONTAINER || true
  docker pull shibme/dictionbot
  echo "Starting: $DICTIONBOT_CONTAINER"
  docker run -e TELEGRAM_BOT_TOKEN --name $DICTIONBOT_CONTAINER --restart always -d shibme/dictionbot
else
  echo "Please install docker client before you begin."
fi
