#!/usr/bin/env bash
DOCKER_VERSION_RESPONSE=$(docker -v)
EXPECTED_RESPONSE="Docker version "
if test "${DOCKER_VERSION_RESPONSE#*$EXPECTED_RESPONSE}" != "$DOCKER_VERSION_RESPONSE"; then
  #Setting default container name if not set
  if [ -z "$DICTIONBOT_CONTAINER" ]; then
    export DICTIONBOT_CONTAINER="dictionbot-container"
  fi
  echo "Attempting to stop and remove any instances of DictionBot..."
  docker stop $DICTIONBOT_CONTAINER || true && docker rm $DICTIONBOT_CONTAINER || true
  docker pull shibme/dictionbot
  echo "Starting: $DICTIONBOT_CONTAINER"
  DICTIONBOT_RUN_COMMAND="docker run -e TELEGRAM_BOT_TOKEN"
  if [ ! -z "$TELEGRAM_BOT_WEBHOOK_URL" ]; then
    DICTIONBOT_RUN_COMMAND="$DICTIONBOT_RUN_COMMAND -e TELEGRAM_BOT_WEBHOOK_URL -p 3428:3428"
  fi
  DICTIONBOT_RUN_COMMAND="$DICTIONBOT_RUN_COMMAND --name $DICTIONBOT_CONTAINER --restart always -d shibme/dictionbot"
  echo $DICTIONBOT_RUN_COMMAND | bash
else
  echo "Please install docker client before you begin."
fi
